// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
REST Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
Contact: kafka-clients-proxy-team@confluent.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"bytes"
	"encoding/json"
)

import (
	"reflect"
)

// StreamsGroupSubtopologyDataAllOf struct for StreamsGroupSubtopologyDataAllOf
type StreamsGroupSubtopologyDataAllOf struct {
	// The unique identifier of the Kafka cluster.
	ClusterId string `json:"cluster_id,omitempty"`
	// The unique identifier of the Streams group.
	GroupId string `json:"group_id,omitempty"`
	// The unique identifier of the Streams subtopology.
	SubtopologyId string `json:"subtopology_id,omitempty"`
	// The list of source topics for the subtopology.
	SourceTopics []string `json:"source_topics,omitempty"`
}

// NewStreamsGroupSubtopologyDataAllOf instantiates a new StreamsGroupSubtopologyDataAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamsGroupSubtopologyDataAllOf(clusterId string, groupId string, subtopologyId string, sourceTopics []string) *StreamsGroupSubtopologyDataAllOf {
	this := StreamsGroupSubtopologyDataAllOf{}
	this.ClusterId = clusterId
	this.GroupId = groupId
	this.SubtopologyId = subtopologyId
	this.SourceTopics = sourceTopics
	return &this
}

// NewStreamsGroupSubtopologyDataAllOfWithDefaults instantiates a new StreamsGroupSubtopologyDataAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamsGroupSubtopologyDataAllOfWithDefaults() *StreamsGroupSubtopologyDataAllOf {
	this := StreamsGroupSubtopologyDataAllOf{}
	return &this
}

// GetClusterId returns the ClusterId field value
func (o *StreamsGroupSubtopologyDataAllOf) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupSubtopologyDataAllOf) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *StreamsGroupSubtopologyDataAllOf) SetClusterId(v string) {
	o.ClusterId = v
}

// GetGroupId returns the GroupId field value
func (o *StreamsGroupSubtopologyDataAllOf) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupSubtopologyDataAllOf) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *StreamsGroupSubtopologyDataAllOf) SetGroupId(v string) {
	o.GroupId = v
}

// GetSubtopologyId returns the SubtopologyId field value
func (o *StreamsGroupSubtopologyDataAllOf) GetSubtopologyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubtopologyId
}

// GetSubtopologyIdOk returns a tuple with the SubtopologyId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupSubtopologyDataAllOf) GetSubtopologyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubtopologyId, true
}

// SetSubtopologyId sets field value
func (o *StreamsGroupSubtopologyDataAllOf) SetSubtopologyId(v string) {
	o.SubtopologyId = v
}

// GetSourceTopics returns the SourceTopics field value
func (o *StreamsGroupSubtopologyDataAllOf) GetSourceTopics() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SourceTopics
}

// GetSourceTopicsOk returns a tuple with the SourceTopics field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupSubtopologyDataAllOf) GetSourceTopicsOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceTopics, true
}

// SetSourceTopics sets field value
func (o *StreamsGroupSubtopologyDataAllOf) SetSourceTopics(v []string) {
	o.SourceTopics = v
}

// Redact resets all sensitive fields to their zero value.
func (o *StreamsGroupSubtopologyDataAllOf) Redact() {
	o.recurseRedact(&o.ClusterId)
	o.recurseRedact(&o.GroupId)
	o.recurseRedact(&o.SubtopologyId)
	o.recurseRedact(&o.SourceTopics)
}

func (o *StreamsGroupSubtopologyDataAllOf) recurseRedact(v interface{}) {
	type redactor interface {
		Redact()
	}
	if r, ok := v.(redactor); ok {
		r.Redact()
	} else {
		val := reflect.ValueOf(v)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch val.Kind() {
		case reflect.Slice, reflect.Array:
			for i := 0; i < val.Len(); i++ {
				// support data types declared without pointers
				o.recurseRedact(val.Index(i).Interface())
				// ... and data types that were declared without but need pointers (for Redact)
				if val.Index(i).CanAddr() {
					o.recurseRedact(val.Index(i).Addr().Interface())
				}
			}
		}
	}
}

func (o StreamsGroupSubtopologyDataAllOf) zeroField(v interface{}) {
	p := reflect.ValueOf(v).Elem()
	p.Set(reflect.Zero(p.Type()))
}

func (o StreamsGroupSubtopologyDataAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if true {
		toSerialize["group_id"] = o.GroupId
	}
	if true {
		toSerialize["subtopology_id"] = o.SubtopologyId
	}
	if true {
		toSerialize["source_topics"] = o.SourceTopics
	}
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(toSerialize)
	return buffer.Bytes(), err
}

type NullableStreamsGroupSubtopologyDataAllOf struct {
	value *StreamsGroupSubtopologyDataAllOf
	isSet bool
}

func (v NullableStreamsGroupSubtopologyDataAllOf) Get() *StreamsGroupSubtopologyDataAllOf {
	return v.value
}

func (v *NullableStreamsGroupSubtopologyDataAllOf) Set(val *StreamsGroupSubtopologyDataAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamsGroupSubtopologyDataAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamsGroupSubtopologyDataAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamsGroupSubtopologyDataAllOf(val *StreamsGroupSubtopologyDataAllOf) *NullableStreamsGroupSubtopologyDataAllOf {
	return &NullableStreamsGroupSubtopologyDataAllOf{value: val, isSet: true}
}

func (v NullableStreamsGroupSubtopologyDataAllOf) MarshalJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(v.value)
	return buffer.Bytes(), err
}

func (v *NullableStreamsGroupSubtopologyDataAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
