// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
REST Admin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.0
Contact: kafka-clients-proxy-team@confluent.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v3

import (
	"bytes"
	"encoding/json"
)

import (
	"reflect"
)

// StreamsGroupMemberAssignmentData The assignment details of a Streams group member.
type StreamsGroupMemberAssignmentData struct {
	Kind     string           `json:"kind,omitempty"`
	Metadata ResourceMetadata `json:"metadata,omitempty"`
	// The unique identifier of the Kafka cluster.
	ClusterId string `json:"cluster_id,omitempty"`
	// The unique identifier of the Streams group.
	GroupId string `json:"group_id,omitempty"`
	// The unique identifier of the Streams group member.
	MemberId     string       `json:"member_id,omitempty"`
	ActiveTasks  Relationship `json:"active_tasks,omitempty"`
	StandbyTasks Relationship `json:"standby_tasks,omitempty"`
	WarmupTasks  Relationship `json:"warmup_tasks,omitempty"`
}

// NewStreamsGroupMemberAssignmentData instantiates a new StreamsGroupMemberAssignmentData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamsGroupMemberAssignmentData(kind string, metadata ResourceMetadata, clusterId string, groupId string, memberId string, activeTasks Relationship, standbyTasks Relationship, warmupTasks Relationship) *StreamsGroupMemberAssignmentData {
	this := StreamsGroupMemberAssignmentData{}
	this.Kind = kind
	this.Metadata = metadata
	this.ClusterId = clusterId
	this.GroupId = groupId
	this.MemberId = memberId
	this.ActiveTasks = activeTasks
	this.StandbyTasks = standbyTasks
	this.WarmupTasks = warmupTasks
	return &this
}

// NewStreamsGroupMemberAssignmentDataWithDefaults instantiates a new StreamsGroupMemberAssignmentData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamsGroupMemberAssignmentDataWithDefaults() *StreamsGroupMemberAssignmentData {
	this := StreamsGroupMemberAssignmentData{}
	return &this
}

// GetKind returns the Kind field value
func (o *StreamsGroupMemberAssignmentData) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *StreamsGroupMemberAssignmentData) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *StreamsGroupMemberAssignmentData) GetMetadata() ResourceMetadata {
	if o == nil {
		var ret ResourceMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetMetadataOk() (*ResourceMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *StreamsGroupMemberAssignmentData) SetMetadata(v ResourceMetadata) {
	o.Metadata = v
}

// GetClusterId returns the ClusterId field value
func (o *StreamsGroupMemberAssignmentData) GetClusterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetClusterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterId, true
}

// SetClusterId sets field value
func (o *StreamsGroupMemberAssignmentData) SetClusterId(v string) {
	o.ClusterId = v
}

// GetGroupId returns the GroupId field value
func (o *StreamsGroupMemberAssignmentData) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *StreamsGroupMemberAssignmentData) SetGroupId(v string) {
	o.GroupId = v
}

// GetMemberId returns the MemberId field value
func (o *StreamsGroupMemberAssignmentData) GetMemberId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemberId
}

// GetMemberIdOk returns a tuple with the MemberId field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetMemberIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberId, true
}

// SetMemberId sets field value
func (o *StreamsGroupMemberAssignmentData) SetMemberId(v string) {
	o.MemberId = v
}

// GetActiveTasks returns the ActiveTasks field value
func (o *StreamsGroupMemberAssignmentData) GetActiveTasks() Relationship {
	if o == nil {
		var ret Relationship
		return ret
	}

	return o.ActiveTasks
}

// GetActiveTasksOk returns a tuple with the ActiveTasks field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetActiveTasksOk() (*Relationship, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveTasks, true
}

// SetActiveTasks sets field value
func (o *StreamsGroupMemberAssignmentData) SetActiveTasks(v Relationship) {
	o.ActiveTasks = v
}

// GetStandbyTasks returns the StandbyTasks field value
func (o *StreamsGroupMemberAssignmentData) GetStandbyTasks() Relationship {
	if o == nil {
		var ret Relationship
		return ret
	}

	return o.StandbyTasks
}

// GetStandbyTasksOk returns a tuple with the StandbyTasks field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetStandbyTasksOk() (*Relationship, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StandbyTasks, true
}

// SetStandbyTasks sets field value
func (o *StreamsGroupMemberAssignmentData) SetStandbyTasks(v Relationship) {
	o.StandbyTasks = v
}

// GetWarmupTasks returns the WarmupTasks field value
func (o *StreamsGroupMemberAssignmentData) GetWarmupTasks() Relationship {
	if o == nil {
		var ret Relationship
		return ret
	}

	return o.WarmupTasks
}

// GetWarmupTasksOk returns a tuple with the WarmupTasks field value
// and a boolean to check if the value has been set.
func (o *StreamsGroupMemberAssignmentData) GetWarmupTasksOk() (*Relationship, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarmupTasks, true
}

// SetWarmupTasks sets field value
func (o *StreamsGroupMemberAssignmentData) SetWarmupTasks(v Relationship) {
	o.WarmupTasks = v
}

// Redact resets all sensitive fields to their zero value.
func (o *StreamsGroupMemberAssignmentData) Redact() {
	o.recurseRedact(&o.Kind)
	o.recurseRedact(&o.Metadata)
	o.recurseRedact(&o.ClusterId)
	o.recurseRedact(&o.GroupId)
	o.recurseRedact(&o.MemberId)
	o.recurseRedact(&o.ActiveTasks)
	o.recurseRedact(&o.StandbyTasks)
	o.recurseRedact(&o.WarmupTasks)
}

func (o *StreamsGroupMemberAssignmentData) recurseRedact(v interface{}) {
	type redactor interface {
		Redact()
	}
	if r, ok := v.(redactor); ok {
		r.Redact()
	} else {
		val := reflect.ValueOf(v)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch val.Kind() {
		case reflect.Slice, reflect.Array:
			for i := 0; i < val.Len(); i++ {
				// support data types declared without pointers
				o.recurseRedact(val.Index(i).Interface())
				// ... and data types that were declared without but need pointers (for Redact)
				if val.Index(i).CanAddr() {
					o.recurseRedact(val.Index(i).Addr().Interface())
				}
			}
		}
	}
}

func (o StreamsGroupMemberAssignmentData) zeroField(v interface{}) {
	p := reflect.ValueOf(v).Elem()
	p.Set(reflect.Zero(p.Type()))
}

func (o StreamsGroupMemberAssignmentData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["cluster_id"] = o.ClusterId
	}
	if true {
		toSerialize["group_id"] = o.GroupId
	}
	if true {
		toSerialize["member_id"] = o.MemberId
	}
	if true {
		toSerialize["active_tasks"] = o.ActiveTasks
	}
	if true {
		toSerialize["standby_tasks"] = o.StandbyTasks
	}
	if true {
		toSerialize["warmup_tasks"] = o.WarmupTasks
	}
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(toSerialize)
	return buffer.Bytes(), err
}

type NullableStreamsGroupMemberAssignmentData struct {
	value *StreamsGroupMemberAssignmentData
	isSet bool
}

func (v NullableStreamsGroupMemberAssignmentData) Get() *StreamsGroupMemberAssignmentData {
	return v.value
}

func (v *NullableStreamsGroupMemberAssignmentData) Set(val *StreamsGroupMemberAssignmentData) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamsGroupMemberAssignmentData) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamsGroupMemberAssignmentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamsGroupMemberAssignmentData(val *StreamsGroupMemberAssignmentData) *NullableStreamsGroupMemberAssignmentData {
	return &NullableStreamsGroupMemberAssignmentData{value: val, isSet: true}
}

func (v NullableStreamsGroupMemberAssignmentData) MarshalJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(v.value)
	return buffer.Bytes(), err
}

func (v *NullableStreamsGroupMemberAssignmentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
