// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
SQL API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: flink-control-plane@confluent.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
)

import (
	"reflect"
)

// SqlV1PhysicalColumn Physical columns define the structure of the table and the data types of its fields.
type SqlV1PhysicalColumn struct {
	Name interface{} `json:"name,omitempty"`
	Type interface{} `json:"type,omitempty"`
	// A comment or description for the column.
	Comment *string `json:"comment,omitempty"`
	// The kind of column.
	Kind string `json:"kind,omitempty"`
}

// NewSqlV1PhysicalColumn instantiates a new SqlV1PhysicalColumn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSqlV1PhysicalColumn(name interface{}, type_ interface{}, kind string) *SqlV1PhysicalColumn {
	this := SqlV1PhysicalColumn{}
	this.Name = name
	this.Type = type_
	this.Kind = kind
	return &this
}

// NewSqlV1PhysicalColumnWithDefaults instantiates a new SqlV1PhysicalColumn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSqlV1PhysicalColumnWithDefaults() *SqlV1PhysicalColumn {
	this := SqlV1PhysicalColumn{}
	return &this
}

// GetName returns the Name field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SqlV1PhysicalColumn) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SqlV1PhysicalColumn) GetNameOk() (*interface{}, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SqlV1PhysicalColumn) SetName(v interface{}) {
	o.Name = v
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SqlV1PhysicalColumn) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SqlV1PhysicalColumn) GetTypeOk() (*interface{}, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SqlV1PhysicalColumn) SetType(v interface{}) {
	o.Type = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *SqlV1PhysicalColumn) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SqlV1PhysicalColumn) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *SqlV1PhysicalColumn) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *SqlV1PhysicalColumn) SetComment(v string) {
	o.Comment = &v
}

// GetKind returns the Kind field value
func (o *SqlV1PhysicalColumn) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SqlV1PhysicalColumn) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SqlV1PhysicalColumn) SetKind(v string) {
	o.Kind = v
}

// Redact resets all sensitive fields to their zero value.
func (o *SqlV1PhysicalColumn) Redact() {
	o.recurseRedact(&o.Name)
	o.recurseRedact(&o.Type)
	o.recurseRedact(o.Comment)
	o.recurseRedact(&o.Kind)
}

func (o *SqlV1PhysicalColumn) recurseRedact(v interface{}) {
	type redactor interface {
		Redact()
	}
	if r, ok := v.(redactor); ok {
		r.Redact()
	} else {
		val := reflect.ValueOf(v)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch val.Kind() {
		case reflect.Slice, reflect.Array:
			for i := 0; i < val.Len(); i++ {
				// support data types declared without pointers
				o.recurseRedact(val.Index(i).Interface())
				// ... and data types that were declared without but need pointers (for Redact)
				if val.Index(i).CanAddr() {
					o.recurseRedact(val.Index(i).Addr().Interface())
				}
			}
		}
	}
}

func (o SqlV1PhysicalColumn) zeroField(v interface{}) {
	p := reflect.ValueOf(v).Elem()
	p.Set(reflect.Zero(p.Type()))
}

func (o SqlV1PhysicalColumn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(toSerialize)
	return buffer.Bytes(), err
}

type NullableSqlV1PhysicalColumn struct {
	value *SqlV1PhysicalColumn
	isSet bool
}

func (v NullableSqlV1PhysicalColumn) Get() *SqlV1PhysicalColumn {
	return v.value
}

func (v *NullableSqlV1PhysicalColumn) Set(val *SqlV1PhysicalColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableSqlV1PhysicalColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableSqlV1PhysicalColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSqlV1PhysicalColumn(val *SqlV1PhysicalColumn) *NullableSqlV1PhysicalColumn {
	return &NullableSqlV1PhysicalColumn{value: val, isSet: true}
}

func (v NullableSqlV1PhysicalColumn) MarshalJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(v.value)
	return buffer.Bytes(), err
}

func (v *NullableSqlV1PhysicalColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
