// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
SQL API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
Contact: flink-control-plane@confluent.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
)

import (
	"reflect"
)

// SqlV1ComputedColumnAllOf struct for SqlV1ComputedColumnAllOf
type SqlV1ComputedColumnAllOf struct {
	Name interface{} `json:"name,omitempty"`
	Type interface{} `json:"type,omitempty"`
	// The kind of column.
	Kind string `json:"kind,omitempty"`
	// The SQL expression used to compute the column value.
	Expression string `json:"expression,omitempty"`
	// Indicates if the computed column is virtual.
	Virtual *bool `json:"virtual,omitempty"`
}

// NewSqlV1ComputedColumnAllOf instantiates a new SqlV1ComputedColumnAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSqlV1ComputedColumnAllOf(kind string, expression string) *SqlV1ComputedColumnAllOf {
	this := SqlV1ComputedColumnAllOf{}
	this.Kind = kind
	this.Expression = expression
	var virtual bool = false
	this.Virtual = &virtual
	return &this
}

// NewSqlV1ComputedColumnAllOfWithDefaults instantiates a new SqlV1ComputedColumnAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSqlV1ComputedColumnAllOfWithDefaults() *SqlV1ComputedColumnAllOf {
	this := SqlV1ComputedColumnAllOf{}
	var virtual bool = false
	this.Virtual = &virtual
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SqlV1ComputedColumnAllOf) GetName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SqlV1ComputedColumnAllOf) GetNameOk() (*interface{}, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return &o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SqlV1ComputedColumnAllOf) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given interface{} and assigns it to the Name field.
func (o *SqlV1ComputedColumnAllOf) SetName(v interface{}) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SqlV1ComputedColumnAllOf) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SqlV1ComputedColumnAllOf) GetTypeOk() (*interface{}, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return &o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SqlV1ComputedColumnAllOf) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given interface{} and assigns it to the Type field.
func (o *SqlV1ComputedColumnAllOf) SetType(v interface{}) {
	o.Type = v
}

// GetKind returns the Kind field value
func (o *SqlV1ComputedColumnAllOf) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *SqlV1ComputedColumnAllOf) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *SqlV1ComputedColumnAllOf) SetKind(v string) {
	o.Kind = v
}

// GetExpression returns the Expression field value
func (o *SqlV1ComputedColumnAllOf) GetExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value
// and a boolean to check if the value has been set.
func (o *SqlV1ComputedColumnAllOf) GetExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expression, true
}

// SetExpression sets field value
func (o *SqlV1ComputedColumnAllOf) SetExpression(v string) {
	o.Expression = v
}

// GetVirtual returns the Virtual field value if set, zero value otherwise.
func (o *SqlV1ComputedColumnAllOf) GetVirtual() bool {
	if o == nil || o.Virtual == nil {
		var ret bool
		return ret
	}
	return *o.Virtual
}

// GetVirtualOk returns a tuple with the Virtual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SqlV1ComputedColumnAllOf) GetVirtualOk() (*bool, bool) {
	if o == nil || o.Virtual == nil {
		return nil, false
	}
	return o.Virtual, true
}

// HasVirtual returns a boolean if a field has been set.
func (o *SqlV1ComputedColumnAllOf) HasVirtual() bool {
	if o != nil && o.Virtual != nil {
		return true
	}

	return false
}

// SetVirtual gets a reference to the given bool and assigns it to the Virtual field.
func (o *SqlV1ComputedColumnAllOf) SetVirtual(v bool) {
	o.Virtual = &v
}

// Redact resets all sensitive fields to their zero value.
func (o *SqlV1ComputedColumnAllOf) Redact() {
	o.recurseRedact(o.Name)
	o.recurseRedact(o.Type)
	o.recurseRedact(&o.Kind)
	o.recurseRedact(&o.Expression)
	o.recurseRedact(o.Virtual)
}

func (o *SqlV1ComputedColumnAllOf) recurseRedact(v interface{}) {
	type redactor interface {
		Redact()
	}
	if r, ok := v.(redactor); ok {
		r.Redact()
	} else {
		val := reflect.ValueOf(v)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch val.Kind() {
		case reflect.Slice, reflect.Array:
			for i := 0; i < val.Len(); i++ {
				// support data types declared without pointers
				o.recurseRedact(val.Index(i).Interface())
				// ... and data types that were declared without but need pointers (for Redact)
				if val.Index(i).CanAddr() {
					o.recurseRedact(val.Index(i).Addr().Interface())
				}
			}
		}
	}
}

func (o SqlV1ComputedColumnAllOf) zeroField(v interface{}) {
	p := reflect.ValueOf(v).Elem()
	p.Set(reflect.Zero(p.Type()))
}

func (o SqlV1ComputedColumnAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["expression"] = o.Expression
	}
	if o.Virtual != nil {
		toSerialize["virtual"] = o.Virtual
	}
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(toSerialize)
	return buffer.Bytes(), err
}

type NullableSqlV1ComputedColumnAllOf struct {
	value *SqlV1ComputedColumnAllOf
	isSet bool
}

func (v NullableSqlV1ComputedColumnAllOf) Get() *SqlV1ComputedColumnAllOf {
	return v.value
}

func (v *NullableSqlV1ComputedColumnAllOf) Set(val *SqlV1ComputedColumnAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSqlV1ComputedColumnAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSqlV1ComputedColumnAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSqlV1ComputedColumnAllOf(val *SqlV1ComputedColumnAllOf) *NullableSqlV1ComputedColumnAllOf {
	return &NullableSqlV1ComputedColumnAllOf{value: val, isSet: true}
}

func (v NullableSqlV1ComputedColumnAllOf) MarshalJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(v.value)
	return buffer.Bytes(), err
}

func (v *NullableSqlV1ComputedColumnAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
