// Copyright 2021 Confluent Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Kafka Connect APIs

REST API for managing connectors

API version: 1.0
Contact: connect@confluent.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
)

import (
	"reflect"
)

// ConnectV1Offsets Array of offsets which are categorised into partitions.
type ConnectV1Offsets struct {
	Items []map[string]interface{}
}

// NewConnectV1Offsets instantiates a new ConnectV1Offsets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectV1Offsets() *ConnectV1Offsets {
	this := ConnectV1Offsets{}
	return &this
}

// NewConnectV1OffsetsWithDefaults instantiates a new ConnectV1Offsets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectV1OffsetsWithDefaults() *ConnectV1Offsets {
	this := ConnectV1Offsets{}
	return &this
}

// Redact resets all sensitive fields to their zero value.
func (o *ConnectV1Offsets) Redact() {
}

func (o *ConnectV1Offsets) recurseRedact(v interface{}) {
	type redactor interface {
		Redact()
	}
	if r, ok := v.(redactor); ok {
		r.Redact()
	} else {
		val := reflect.ValueOf(v)
		if val.Kind() == reflect.Ptr {
			val = val.Elem()
		}
		switch val.Kind() {
		case reflect.Slice, reflect.Array:
			for i := 0; i < val.Len(); i++ {
				// support data types declared without pointers
				o.recurseRedact(val.Index(i).Interface())
				// ... and data types that were declared without but need pointers (for Redact)
				if val.Index(i).CanAddr() {
					o.recurseRedact(val.Index(i).Addr().Interface())
				}
			}
		}
	}
}

func (o ConnectV1Offsets) zeroField(v interface{}) {
	p := reflect.ValueOf(v).Elem()
	p.Set(reflect.Zero(p.Type()))
}

func (o ConnectV1Offsets) MarshalJSON() ([]byte, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(toSerialize)
	return buffer.Bytes(), err
}

func (o *ConnectV1Offsets) UnmarshalJSON(bytes []byte) (err error) {
	return json.Unmarshal(bytes, &o.Items)
}

type NullableConnectV1Offsets struct {
	value *ConnectV1Offsets
	isSet bool
}

func (v NullableConnectV1Offsets) Get() *ConnectV1Offsets {
	return v.value
}

func (v *NullableConnectV1Offsets) Set(val *ConnectV1Offsets) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectV1Offsets) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectV1Offsets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectV1Offsets(val *ConnectV1Offsets) *NullableConnectV1Offsets {
	return &NullableConnectV1Offsets{value: val, isSet: true}
}

func (v NullableConnectV1Offsets) MarshalJSON() ([]byte, error) {
	buffer := &bytes.Buffer{}
	encoder := json.NewEncoder(buffer)
	encoder.SetEscapeHTML(false)
	err := encoder.Encode(v.value)
	return buffer.Bytes(), err
}

func (v *NullableConnectV1Offsets) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
